vuetifyjs/vue-cli-plugins

generator/templates/default/src/plugins/vuetify.js

fix stylus path

---

generator/index.js

Follow the @vue/cli default spaces before <link> tags

fix tabs to spaces

---

README.md

With the 1.0.0-beta of [Vue CLI plugin Electron Builder](https://nklayman.github.io/vue-cli-plugin-electron-builder/), both the App/HelloWorld overwrite issue and the material icons issues are resolved. I removed them from the `README.md` and updated the url for vcp-electron-builder.
Also, the `App.vue` and `HelloWorld.vue` files should have never been overwritten by vcp-electron-builder.

Update electron-builder integration guide

---

index.js

This is a better practice since now end users can use the `chainWepack` API to access this plugin, e.g. to remove it, or pass options to it once (if ever) the plugin supports that.
I realize that this is not a very significant change for the moment but as a general rule it's better to use chainWebpack as a plugin author to give the maximum control over the resulting config to the end user.

Use chainWebpack instead of configureWebpack to add Loader plugin

---

index.js

`vue-loader` does not automatically `require` assets referenced in the `src` attribute of a [`<v-img>`](https://vuetifyjs.com/en/components/images) tag. This change makes `<v-img>` [work with `vue-loader`](https://vue-loader.vuejs.org/options.html#transformasseturls) in the same way that `<img>` does.
Template markup looking like `<v-img src="@/assets/logo.png">` will now compile properly.

Support asset references from v-img

---

package.json
util/__tests__/__snapshots__/helpers.spec.js.snap
util/helpers.js

fixes https://github.com/vuetifyjs/vue-cli-plugin-vuetify/issues/119.
We should probably also install 8.0.0 in our generator (https://github.com/vuetifyjs/vue-cli-plugin-vuetify/blob/dev/generator/tools/alaCarte.js#L6) 
Since @vue/cli now also installs 8.0.0 ever since `3.12.0` and `4.0.0-rc4`

fix: add support for sass-loader > 8.0.0

---

generator/tools/alaCarte.js

This can land after: https://github.com/vuetifyjs/vue-cli-plugin-vuetify/pull/122
Newer versions of `@vue/cli` will install version `8.0.0` by default, so we can do it aswell to avoid warnings in the console.
Might be semver minor? I'm not sure since the generator only runs once, so it would only apply for new projects.

Feat: prefer sass loader v8

---

util/helpers.js

As said in vuetifyjs/vue-cli-plugin-vuetify#128, this plugin shouldn't overwrite sass-loader configuration that's defined in user's `vue.config.js` but instead append its rules to it.

fix: include user-defined css loader options

---

README.md

Added instructions on readme for using [capacitor](https://capacitor.ionicframework.com/) to make mobile apps. There wasn't an old template for it, but it seemed like a good idea to add it as many people prefer it over cordova. It is more modern and in my experience has less bugs.

Add capacitor instructions to README

---

packages/cli-plugin-utils/package.json
packages/vue-cli-plugin-vuetify/package.json

`vue-cli-plugin-vuetify` [depends](https://github.com/vuetifyjs/vue-cli-plugins/blob/5ad63c05fa03b9696546c3a0abe608e5c7ccb485/packages/vue-cli-plugin-vuetify/util/helpers.js#L2) on `semver`, but doesn't declare it as a dependency, which causes Yarn 2 PnP to throw `Error: A package is trying to access another package without the second one being listed as a dependency of the first one` when used inside a project.
This PR adds `semver` as a dependency to `vue-cli-plugin-vuetify`, as well as to `@vuetify/cli-plugin-utils` (since I've noticed it has [the same issue](https://github.com/vuetifyjs/vue-cli-plugins/blob/5ad63c05fa03b9696546c3a0abe608e5c7ccb485/packages/cli-plugin-utils/index.js#L2)).
This PR preserves the version of semver (`^6.3.0`) that is declared as a `devDependency` in the …

fix(dependencies): add undeclared dependencies

---

packages/vue-cli-plugin-vuetify/util/helpers.js

Sass-loader v9 has replaced prependData with additionalData.
This pr replaces the prependData option/syntax with addtionalData when sass-loader v9 or higher is in use

 fix(sass-loader): prependData removed from v9

---

packages/vue-cli-plugin-vuetify/package.json
yarn.lock

Fix issue in https://github.com/vuetifyjs/vue-cli-plugins/issues/101
On the fresh project adding the `vue add vuetify` plugin results in a missing dependency:
```
WEBPACK  Failed to compile with 9 error(s)
Error in ./node_modules/vuetify/lib/components/VImg/VImg.js
Module not found: 'null-loader' in '/Users/user/temp/vuetify-create-test'
```

fix: add missing null-loader dependency

---

packages/vue-cli-plugin-vuetify/index.js

**What's the problem this PR addresses?**
`vue-cli-plugin-vuetify` adds webpack loaders using their name instead of location causing it to depend on hoisting, and to not work under Yarn PnP.
**How did you fix it?**
Use `require.resolve` when adding loaders

fix: use require.resolve for loaders

---

packages/vue-cli-plugin-vuetify/generator/templates/default/src/plugins/vuetify.js

In my case, `lang.current` was set to `zh-Hans` but the correct should be `zhHans`.

fix(template): update current lang

---

packages/vue-cli-plugin-vuetify/index.js

Hi guys.
I'm using `vuetify` via `vue-cli-plugin-vuetify` at work. 
Yesterday I added `@yzfe/svgicon` plugin for using `*svg` as vue' component and noticed that usage over docs' example doesn't work (see https://mmf-fe.github.io/svgicon/en/guide/#usage). It simply didn't load svg over `<icon data="@icon/arrow.svg" />` method.
```
<template>
<div>
<icon data="@icon/arrow.svg" />
</div>
</template>
```
`@icon` is configured alias at `.vue-svgicon.config.js` config of `@yzfe/svgicon` plugin.
I tried to install `@yzfe/svgicon` plugin in newly created vue project over `vue create project-name` and it worked. Then I installed `vuetify` over `vue add vuetify` command and icon plugin stoped working.
After some time spent for researching I discovered that yours vue-loader' config doesn't merge …

fix: merge `transformAssetUrls` options

---

packages/@vuetify/cli-plugin-utils/index.js

sass-loader >= 9 introduced a breaking change, removing `prependData` in favor of `additionalData`
https://github.com/webpack-contrib/sass-loader/releases/tag/v9.0.0

fix(utils): Add support for sass-loader >= 9

---

packages/vue-cli-plugin-vuetify/generator/index.js
packages/vue-cli-plugin-vuetify/generator/tools/alaCarte.js
packages/vue-cli-plugin-vuetify/generator/tools/vuetify.js

This will ensure that javascript settings are not lost in `vue.congih.js`, as the current method writes the same using a` JSON.stringify`.
In this way, configurations made previously of adding vuetify via plugin or even presets, do not lose configurations that use javascript.

fix: use extendPackage to write transpileDependencies

---

packages/vue-cli-plugin-vuetify-storybook/generator/template/_storybook/addon-vuetify/decorator.js

Allow passing config-level options to decorator.
For example if you have own theme options it's convenient to pass it in config like this:
```
addDecorator(withVuetify({
theme: {
dark: false,
themes: {
light: {
primary: '#9C27B2',
},
},
},
}));
```

feat(storybook): add config-level options

---

packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-basil/package.json
packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-crane/package.json
packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-fortnightly/package.json
packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-owl/package.json
packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-rally/package.json
packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-reply/package.json
packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-shrine/package.json

This seems to fix the issues people have been having with `sass-loader` and the Material Studies presets.

fix(material-studies): bump utils pkg version.

---

packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-rally/package.json

I think this fixes #241 for the rally plugin.

fix(preset-rally): sass-loader incompatibility.

---

packages/vue-cli-plugin-vuetify/index.js
packages/vue-cli-plugin-vuetify/package.json
yarn.lock

Note: absolutely not tested, not familiar with chain-webpack, etc.
This should fix: https://github.com/vuetifyjs/vue-cli-plugins/issues/254
Relevant: https://github.com/vuetifyjs/vue-cli-plugins/pull/152
The chain webpack types don't seem to thing that an alias can be false, it appears that they are not up to date with webpack on this: https://webpack.js.org/configuration/resolve/#resolvealias
I thought I'd give it a try, but this is a bit out of my league

Removed deprecated null-loader dependency

---

packages/vue-cli-plugin-vuetify/generator/tools/vite.js

Update the installed version for `vite` and `@vitejs/plugin-vue` when using the Vuetify 3 Preview preset.

fix(preview): install correct vite version.

---

packages/vue-cli-plugin-vuetify/generator/tools/alaCarte.js

Force install the following when generating a Vue 3 and Vuetify 3 project:
- `@vue/cli-service`: `5.0.0-beta.7`
- `@vue/cli-plugin-babel`: `5.0.0-beta.7`

chore(vuetify-cli): Install latest beta version for vue cli plugins.

---

packages/vue-cli-plugin-vuetify/generator/index.js
packages/vue-cli-plugin-vuetify/generator/templates/v3/vite/vite.config.js

- Vite config: Remove `styles: 'expose'`
- Remove vue.config.js for projects generated with Vite.

fix(v3): Update vite config

---

packages/vue-cli-plugin-vuetify/generator/index.js
packages/vue-cli-plugin-vuetify/generator/templates/v3/vite/vite.config.ts
packages/vue-cli-plugin-vuetify/generator/tools/vite.js

- Injects `vite-plugin-vuetify` plugin into the Vite config when a project is generated with the `vue-create` package
- Add correct `vite-plugin-vuetify` Vite config import when generating a TS project with `vue-cli-plugins` 
- Updates ESBuild target for JS Vite projects generated with a `jsconfig.json` file: Replaces `'es5'` with `'esnext'`
- Stop installing `webpack-plugin-vuetify` when the project is a Vite project

refactor(vite): handle config for create-vue projects 
