vuetifyjs/vue-cli-plugins

- README.md
The `vue add vuetify` command will automatically install it as a dev dependency and invoke it.
> Update install command in readme

- generator/index.js
- generator/tools/polyfill.js
> feat: replace correct ie version

- prompts.js
Added Serbian (cyrillic) to the list of supported locales.
> Added Serbian (cyrillic)

- util/locales.js
Also see: https://github.com/vuetifyjs/vuetify/pull/5385 and https://github.com/vuetifyjs/vuetifyjs.com/pull/645
> Added Afrikaans to the LOCALE_MAP

- util/locales.js
See [Added Romanian translation #6030](https://github.com/vuetifyjs/vuetify/pull/6030#pullrequestreview-188737215)
> Added ro: Romanian locale

- generator/helpers.js
- generator/index.js
- package.json
Was testing, and working through errors
Not finished yet.
> started work on finishing this.

- util/locales.js
[Related PR  Vuetify:dev](https://github.com/vuetifyjs/vuetify/pull/6125)
> Add Croatian locale

- util/locales.js
Added Arabic locale as requested per `vuetify` PR [#6291](https://github.com/vuetifyjs/vuetify/pull/6291)
> Added Arabic locale

- util/locales.js
> added turkish locale

- util/locales.js
It is related to this PR. https://github.com/vuetifyjs/vuetify/pull/7352
> Add korean locale key to locales.js

- util/locales.js
Related to https://github.com/vuetifyjs/vuetify/pull/7587
> feat(locale): add Norwegian translation

- util/locales.js
Related to [https://github.com/vuetifyjs/vuetify/pull/8228](https://github.com/vuetifyjs/vuetify/pull/8228)
> Added czech translation

- package.json
- yarn.lock
@johnleider
Running `rm -rf node_modules` + `yarn clean cache` + `yarn` fails currently on `master`
> chore: lockfile maintenance

- packages/vue-cli-plugin-vuetify/util/locales.js
This is the corresponding pull request for vue-cli-plugins, related to https://github.com/vuetifyjs/vuetify/pull/10381.
> feat(locale): add Finnish locale

- packages/vue-cli-plugin-vuetify/util/locales.js
Add slovak locale -> PR for vuetify https://github.com/vuetifyjs/vuetify/pull/10328
> feat(locale): add slovak locale

- packages/@vuetify/presets/generator/templates/base/src/layouts/default/AppBar.vue
- packages/@vuetify/presets/generator/templates/base/src/layouts/default/Drawer.vue
- packages/@vuetify/presets/generator/templates/base/src/layouts/default/index.vue
- packages/@vuetify/presets/generator/templates/base/src/store/modules/app.js
Add drawer component to the base template.
> feat(base): Add drawer component

- README.md
Update link urls for the Material Studies preset links.
> docs(README): Update preset links

- packages/vue-cli-plugin-vuetify/util/locales.js
Add bulgarian locale -> PR for vuetify vuetifyjs/vuetify#12649
> feat(locale) Add bulgarian localization

- packages/vue-cli-plugin-vuetify/generator/templates/default/src/plugins/vuetify.js
Fix the problem that some language packs did not load correctly
> fix: camelCase language codes

- packages/vue-cli-plugin-vuetify/util/locales.js
Add Vietnamese translation -> PR for vuetifyjs/vuetify#12977
> feat(locale): Add Vietnamese translation

- packages/vue-cli-plugin-vuetify/util/locales.js
Related [PR on Vuetify part of the repo](https://github.com/vuetifyjs/vuetify/pull/13016)
> feat(locale): add Serbian latin translation

- packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-fortnightly/preset/overrides.sass
imported `varables.scss` at top of the file.
> fix(preset): move style import in fortnightly preset

- packages/@vuetify/material-studies/templates/vue-cli-plugin-vuetify-preset-shrine/preset/overrides.sass
Update icon and text color to adhere to the material study guidelines: [Color](https://material.io/design/material-studies/shrine.html#color)
> fix(preset-shrine): change anchor element color

- packages/vue-cli-plugin-vuetify-storybook/generator/template/_storybook/webpack.config.js
Added `@` to storybook `webpack.config.js` as an alias for `./src` to match default Vue webpack
config.
> feat(webpack.config): add src alias

- packages/vue-cli-plugin-vuetify-storybook/generator/index.js
closes #172 
adding build script
adding `'` to prismjs
> fix(package.json): add missing dependencies and scripts for storybook

- packages/@vuetify/cli-plugin-utils/index.js
> fix(229-utils): Presets don't support ts

- packages/vue-cli-plugin-vuetify/generator/tools/fonts.js
> fix(fonts): @mdi/font version

- packages/vue-cli-plugin-vuetify/generator/tools/fonts.js
Fix font versions in `vue-cli-plugins-vuetify`.
> fix(fonts): specify versions for all font packages.

- packages/vue-cli-plugin-vuetify/generator/templates/default/src/plugins/vuetify.js
Updated the primary color variable value for manual configuration: #007bff
> fix(configure): update css var primary color value.

- packages/vue-cli-plugin-vuetify/generator/index.js
- packages/vue-cli-plugin-vuetify/generator/templates/v3/src/index.vite.html
- packages/vue-cli-plugin-vuetify/generator/tools/vite.js
> fix(vite): Vite preset inserts wrong main entry w/ ts

- packages/vue-cli-plugin-vuetify/util/helpers.js
> fix(sass): #286 inject the correct path based on vuetify version.

- packages/vue-cli-plugin-vuetify/prompts.js
- packages/vue-cli-plugin-vuetify/util/presets.js
Updated Vuetify CLI preset option names and order.
> chore(cli): update preset options.

- packages/@vuetify/presets/generator/templates/base/src/plugins/app.js
Removed `registerComponents` wrapper.
> fix(base): remove wrapper fn from base app plugin.

- package.json
- yarn.lock
Fixes most dependency vulnerabilities.
- Lerna@3.21.0 -> 4.0.0
- Webpack@4.43.0 -> 4.46.0
> chore(deps): bump deps, fix vulnerabilities

- packages/vue-cli-plugin-vuetify/package.json
> Added webpack as a peerDependecy in vue-cli-plugin-vuetify
